name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build App
        run: yarn build
